id: PF5920994
initial_creation_type: ocr
source_metadata:
  volumes:
    0a560629a900437aa3a555c07b99f166:
      base_file: v097.txt
      image_group_id: I1PD95942
      title: ཚད་མ་ཀུན་ལས་བཏུས་པའི་འགྲེལ་པ།
      total_pages: 1198
      volume_number: 97
